// Code generated by MockGen. DO NOT EDIT.
// Source: grpc/user_client.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	userpb "paymentfc/proto/userpb"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUserClient is a mock of UserClient interface.
type MockUserClient struct {
	ctrl     *gomock.Controller
	recorder *MockUserClientMockRecorder
}

// MockUserClientMockRecorder is the mock recorder for MockUserClient.
type MockUserClientMockRecorder struct {
	mock *MockUserClient
}

// NewMockUserClient creates a new mock instance.
func NewMockUserClient(ctrl *gomock.Controller) *MockUserClient {
	mock := &MockUserClient{ctrl: ctrl}
	mock.recorder = &MockUserClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserClient) EXPECT() *MockUserClientMockRecorder {
	return m.recorder
}

// GetUserInfoByUserID mocks base method.
func (m *MockUserClient) GetUserInfoByUserID(ctx context.Context, userID int64) (*userpb.GetUserInfoResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserInfoByUserID", ctx, userID)
	ret0, _ := ret[0].(*userpb.GetUserInfoResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserInfoByUserID indicates an expected call of GetUserInfoByUserID.
func (mr *MockUserClientMockRecorder) GetUserInfoByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserInfoByUserID", reflect.TypeOf((*MockUserClient)(nil).GetUserInfoByUserID), ctx, userID)
}
