version: "3.8"

services:
  vault:
    image: vault:1.13.3
    container_name: vault-dev
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: fcproject
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    cap_add:
     - IPC_LOCK
    volumes:
     - ./vault_data:/vault/file
    command: server -dev